name: service_providers_module
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc_concurrency: ^0.2.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.0.3
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.1.1

flutter:
  assets:
    - assets/
